// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cold_wallets_gen.sql

package repo_wallets_cold

import (
	"context"

	"github.com/dv-net/dv-processing/internal/models"
	"github.com/dv-net/dv-processing/pkg/walletsdk/wconstants"
	"github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO cold_wallets (blockchain, address, owner_id, is_active, created_at)
	VALUES ($1, $2, $3, $4, now())
	RETURNING id, blockchain, address, owner_id, is_active, is_dirty, created_at, updated_at
`

type CreateParams struct {
	Blockchain wconstants.BlockchainType `db:"blockchain" json:"blockchain" validate:"required"`
	Address    string                    `db:"address" json:"address" validate:"required"`
	OwnerID    uuid.UUID                 `db:"owner_id" json:"owner_id" validate:"required,uuid4"`
	IsActive   bool                      `db:"is_active" json:"is_active"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (*models.ColdWallet, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Blockchain,
		arg.Address,
		arg.OwnerID,
		arg.IsActive,
	)
	var i models.ColdWallet
	err := row.Scan(
		&i.ID,
		&i.Blockchain,
		&i.Address,
		&i.OwnerID,
		&i.IsActive,
		&i.IsDirty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
