// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.12
package repo_wallets_cold

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameColdWallets TableName = "cold_wallets"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameColdWalletsId         ColumnName = "id"
	ColumnNameColdWalletsBlockchain ColumnName = "blockchain"
	ColumnNameColdWalletsAddress    ColumnName = "address"
	ColumnNameColdWalletsOwnerId    ColumnName = "owner_id"
	ColumnNameColdWalletsIsActive   ColumnName = "is_active"
	ColumnNameColdWalletsIsDirty    ColumnName = "is_dirty"
	ColumnNameColdWalletsCreatedAt  ColumnName = "created_at"
	ColumnNameColdWalletsUpdatedAt  ColumnName = "updated_at"
)

func ColdWalletsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameColdWalletsId,
		ColumnNameColdWalletsBlockchain,
		ColumnNameColdWalletsAddress,
		ColumnNameColdWalletsOwnerId,
		ColumnNameColdWalletsIsActive,
		ColumnNameColdWalletsIsDirty,
		ColumnNameColdWalletsCreatedAt,
		ColumnNameColdWalletsUpdatedAt,
	}
}
