// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_wallets_cold

import (
	"context"

	"github.com/dv-net/dv-processing/internal/models"
	"github.com/dv-net/dv-processing/pkg/walletsdk/wconstants"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.ColdWallet, error)
	Get(ctx context.Context, arg GetParams) (*models.ColdWallet, error)
	GetAllByOwnerID(ctx context.Context, ownerID uuid.UUID) ([]*models.ColdWallet, error)
	GetByBlockchainAndAddress(ctx context.Context, blockchain wconstants.BlockchainType, address string) (*models.ColdWallet, error)
	MaxSequence(ctx context.Context, blockchain wconstants.BlockchainType, ownerID uuid.UUID) (int32, error)
}

var _ Querier = (*Queries)(nil)
