// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: processing/transfer/v1/transfer.proto

package transferv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dv-net/dv-processing/api/processing/transfer/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TransferServiceName is the fully-qualified name of the TransferService service.
	TransferServiceName = "processing.transfer.v1.TransferService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TransferServiceCreateProcedure is the fully-qualified name of the TransferService's Create RPC.
	TransferServiceCreateProcedure = "/processing.transfer.v1.TransferService/Create"
	// TransferServiceGetByRequestIDProcedure is the fully-qualified name of the TransferService's
	// GetByRequestID RPC.
	TransferServiceGetByRequestIDProcedure = "/processing.transfer.v1.TransferService/GetByRequestID"
	// TransferServiceCancelProcedure is the fully-qualified name of the TransferService's Cancel RPC.
	TransferServiceCancelProcedure = "/processing.transfer.v1.TransferService/Cancel"
	// TransferServiceExecuteNowProcedure is the fully-qualified name of the TransferService's
	// ExecuteNow RPC.
	TransferServiceExecuteNowProcedure = "/processing.transfer.v1.TransferService/ExecuteNow"
)

// TransferServiceClient is a client for the processing.transfer.v1.TransferService service.
type TransferServiceClient interface {
	// Create a new transfer
	Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error)
	// Get transfer by request ID
	GetByRequestID(context.Context, *connect.Request[v1.GetByRequestIDRequest]) (*connect.Response[v1.GetByRequestIDResponse], error)
	// Cancel a scheduled transfer before its execute_after is reached
	Cancel(context.Context, *connect.Request[v1.CancelRequest]) (*connect.Response[v1.CancelResponse], error)
	// Execute a scheduled transfer immediately, confirmed by owner's TOTP
	ExecuteNow(context.Context, *connect.Request[v1.ExecuteNowRequest]) (*connect.Response[v1.ExecuteNowResponse], error)
}

// NewTransferServiceClient constructs a client for the processing.transfer.v1.TransferService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTransferServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TransferServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	transferServiceMethods := v1.File_processing_transfer_v1_transfer_proto.Services().ByName("TransferService").Methods()
	return &transferServiceClient{
		create: connect.NewClient[v1.CreateRequest, v1.CreateResponse](
			httpClient,
			baseURL+TransferServiceCreateProcedure,
			connect.WithSchema(transferServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		getByRequestID: connect.NewClient[v1.GetByRequestIDRequest, v1.GetByRequestIDResponse](
			httpClient,
			baseURL+TransferServiceGetByRequestIDProcedure,
			connect.WithSchema(transferServiceMethods.ByName("GetByRequestID")),
			connect.WithClientOptions(opts...),
		),
		cancel: connect.NewClient[v1.CancelRequest, v1.CancelResponse](
			httpClient,
			baseURL+TransferServiceCancelProcedure,
			connect.WithSchema(transferServiceMethods.ByName("Cancel")),
			connect.WithClientOptions(opts...),
		),
		executeNow: connect.NewClient[v1.ExecuteNowRequest, v1.ExecuteNowResponse](
			httpClient,
			baseURL+TransferServiceExecuteNowProcedure,
			connect.WithSchema(transferServiceMethods.ByName("ExecuteNow")),
			connect.WithClientOptions(opts...),
		),
	}
}

// transferServiceClient implements TransferServiceClient.
type transferServiceClient struct {
	create         *connect.Client[v1.CreateRequest, v1.CreateResponse]
	getByRequestID *connect.Client[v1.GetByRequestIDRequest, v1.GetByRequestIDResponse]
	cancel         *connect.Client[v1.CancelRequest, v1.CancelResponse]
	executeNow     *connect.Client[v1.ExecuteNowRequest, v1.ExecuteNowResponse]
}

// Create calls processing.transfer.v1.TransferService.Create.
func (c *transferServiceClient) Create(ctx context.Context, req *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// GetByRequestID calls processing.transfer.v1.TransferService.GetByRequestID.
func (c *transferServiceClient) GetByRequestID(ctx context.Context, req *connect.Request[v1.GetByRequestIDRequest]) (*connect.Response[v1.GetByRequestIDResponse], error) {
	return c.getByRequestID.CallUnary(ctx, req)
}

// Cancel calls processing.transfer.v1.TransferService.Cancel.
func (c *transferServiceClient) Cancel(ctx context.Context, req *connect.Request[v1.CancelRequest]) (*connect.Response[v1.CancelResponse], error) {
	return c.cancel.CallUnary(ctx, req)
}

// ExecuteNow calls processing.transfer.v1.TransferService.ExecuteNow.
func (c *transferServiceClient) ExecuteNow(ctx context.Context, req *connect.Request[v1.ExecuteNowRequest]) (*connect.Response[v1.ExecuteNowResponse], error) {
	return c.executeNow.CallUnary(ctx, req)
}

// TransferServiceHandler is an implementation of the processing.transfer.v1.TransferService
// service.
type TransferServiceHandler interface {
	// Create a new transfer
	Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error)
	// Get transfer by request ID
	GetByRequestID(context.Context, *connect.Request[v1.GetByRequestIDRequest]) (*connect.Response[v1.GetByRequestIDResponse], error)
	// Cancel a scheduled transfer before its execute_after is reached
	Cancel(context.Context, *connect.Request[v1.CancelRequest]) (*connect.Response[v1.CancelResponse], error)
	// Execute a scheduled transfer immediately, confirmed by owner's TOTP
	ExecuteNow(context.Context, *connect.Request[v1.ExecuteNowRequest]) (*connect.Response[v1.ExecuteNowResponse], error)
}

// NewTransferServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTransferServiceHandler(svc TransferServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	transferServiceMethods := v1.File_processing_transfer_v1_transfer_proto.Services().ByName("TransferService").Methods()
	transferServiceCreateHandler := connect.NewUnaryHandler(
		TransferServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(transferServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	transferServiceGetByRequestIDHandler := connect.NewUnaryHandler(
		TransferServiceGetByRequestIDProcedure,
		svc.GetByRequestID,
		connect.WithSchema(transferServiceMethods.ByName("GetByRequestID")),
		connect.WithHandlerOptions(opts...),
	)
	transferServiceCancelHandler := connect.NewUnaryHandler(
		TransferServiceCancelProcedure,
		svc.Cancel,
		connect.WithSchema(transferServiceMethods.ByName("Cancel")),
		connect.WithHandlerOptions(opts...),
	)
	transferServiceExecuteNowHandler := connect.NewUnaryHandler(
		TransferServiceExecuteNowProcedure,
		svc.ExecuteNow,
		connect.WithSchema(transferServiceMethods.ByName("ExecuteNow")),
		connect.WithHandlerOptions(opts...),
	)
	return "/processing.transfer.v1.TransferService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TransferServiceCreateProcedure:
			transferServiceCreateHandler.ServeHTTP(w, r)
		case TransferServiceGetByRequestIDProcedure:
			transferServiceGetByRequestIDHandler.ServeHTTP(w, r)
		case TransferServiceCancelProcedure:
			transferServiceCancelHandler.ServeHTTP(w, r)
		case TransferServiceExecuteNowProcedure:
			transferServiceExecuteNowHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTransferServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTransferServiceHandler struct{}

func (UnimplementedTransferServiceHandler) Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("processing.transfer.v1.TransferService.Create is not implemented"))
}

func (UnimplementedTransferServiceHandler) GetByRequestID(context.Context, *connect.Request[v1.GetByRequestIDRequest]) (*connect.Response[v1.GetByRequestIDResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("processing.transfer.v1.TransferService.GetByRequestID is not implemented"))
}

func (UnimplementedTransferServiceHandler) Cancel(context.Context, *connect.Request[v1.CancelRequest]) (*connect.Response[v1.CancelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("processing.transfer.v1.TransferService.Cancel is not implemented"))
}

func (UnimplementedTransferServiceHandler) ExecuteNow(context.Context, *connect.Request[v1.ExecuteNowRequest]) (*connect.Response[v1.ExecuteNowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("processing.transfer.v1.TransferService.ExecuteNow is not implemented"))
}
