// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: processing/system/v1/system.proto

package systemv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_processing_system_v1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processing_system_v1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_processing_system_v1_system_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_processing_system_v1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processing_system_v1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_processing_system_v1_system_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

type CheckNewVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckNewVersionRequest) Reset() {
	*x = CheckNewVersionRequest{}
	mi := &file_processing_system_v1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckNewVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckNewVersionRequest) ProtoMessage() {}

func (x *CheckNewVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processing_system_v1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckNewVersionRequest.ProtoReflect.Descriptor instead.
func (*CheckNewVersionRequest) Descriptor() ([]byte, []int) {
	return file_processing_system_v1_system_proto_rawDescGZIP(), []int{2}
}

type CheckNewVersionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InstalledVersion string                 `protobuf:"bytes,2,opt,name=installed_version,json=installedVersion,proto3" json:"installed_version,omitempty"`
	AvailableVersion string                 `protobuf:"bytes,3,opt,name=available_version,json=availableVersion,proto3" json:"available_version,omitempty"`
	NeedForUpdate    bool                   `protobuf:"varint,4,opt,name=need_for_update,json=needForUpdate,proto3" json:"need_for_update,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckNewVersionResponse) Reset() {
	*x = CheckNewVersionResponse{}
	mi := &file_processing_system_v1_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckNewVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckNewVersionResponse) ProtoMessage() {}

func (x *CheckNewVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processing_system_v1_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckNewVersionResponse.ProtoReflect.Descriptor instead.
func (*CheckNewVersionResponse) Descriptor() ([]byte, []int) {
	return file_processing_system_v1_system_proto_rawDescGZIP(), []int{3}
}

func (x *CheckNewVersionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckNewVersionResponse) GetInstalledVersion() string {
	if x != nil {
		return x.InstalledVersion
	}
	return ""
}

func (x *CheckNewVersionResponse) GetAvailableVersion() string {
	if x != nil {
		return x.AvailableVersion
	}
	return ""
}

func (x *CheckNewVersionResponse) GetNeedForUpdate() bool {
	if x != nil {
		return x.NeedForUpdate
	}
	return false
}

type UpdateToNewVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateToNewVersionRequest) Reset() {
	*x = UpdateToNewVersionRequest{}
	mi := &file_processing_system_v1_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateToNewVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateToNewVersionRequest) ProtoMessage() {}

func (x *UpdateToNewVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processing_system_v1_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateToNewVersionRequest.ProtoReflect.Descriptor instead.
func (*UpdateToNewVersionRequest) Descriptor() ([]byte, []int) {
	return file_processing_system_v1_system_proto_rawDescGZIP(), []int{4}
}

type UpdateToNewVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateToNewVersionResponse) Reset() {
	*x = UpdateToNewVersionResponse{}
	mi := &file_processing_system_v1_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateToNewVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateToNewVersionResponse) ProtoMessage() {}

func (x *UpdateToNewVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processing_system_v1_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateToNewVersionResponse.ProtoReflect.Descriptor instead.
func (*UpdateToNewVersionResponse) Descriptor() ([]byte, []int) {
	return file_processing_system_v1_system_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateToNewVersionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetLastLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastLogsRequest) Reset() {
	*x = GetLastLogsRequest{}
	mi := &file_processing_system_v1_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastLogsRequest) ProtoMessage() {}

func (x *GetLastLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processing_system_v1_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLastLogsRequest) Descriptor() ([]byte, []int) {
	return file_processing_system_v1_system_proto_rawDescGZIP(), []int{6}
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_processing_system_v1_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_processing_system_v1_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_processing_system_v1_system_proto_rawDescGZIP(), []int{7}
}

func (x *LogEntry) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLastLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogEntry            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastLogsResponse) Reset() {
	*x = GetLastLogsResponse{}
	mi := &file_processing_system_v1_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastLogsResponse) ProtoMessage() {}

func (x *GetLastLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processing_system_v1_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLastLogsResponse) Descriptor() ([]byte, []int) {
	return file_processing_system_v1_system_proto_rawDescGZIP(), []int{8}
}

func (x *GetLastLogsResponse) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_processing_system_v1_system_proto protoreflect.FileDescriptor

const file_processing_system_v1_system_proto_rawDesc = "" +
	"\n" +
	"!processing/system/v1/system.proto\x12\x14processing.system.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\r\n" +
	"\vInfoRequest\"@\n" +
	"\fInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\"\x18\n" +
	"\x16CheckNewVersionRequest\"\xaf\x01\n" +
	"\x17CheckNewVersionResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x11installed_version\x18\x02 \x01(\tR\x10installedVersion\x12+\n" +
	"\x11available_version\x18\x03 \x01(\tR\x10availableVersion\x12&\n" +
	"\x0fneed_for_update\x18\x04 \x01(\bR\rneedForUpdate\"\x1b\n" +
	"\x19UpdateToNewVersionRequest\"4\n" +
	"\x1aUpdateToNewVersionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x14\n" +
	"\x12GetLastLogsRequest\"j\n" +
	"\bLogEntry\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"I\n" +
	"\x13GetLastLogsResponse\x122\n" +
	"\x04logs\x18\x01 \x03(\v2\x1e.processing.system.v1.LogEntryR\x04logs2\xab\x03\n" +
	"\rSystemService\x12M\n" +
	"\x04Info\x12!.processing.system.v1.InfoRequest\x1a\".processing.system.v1.InfoResponse\x12n\n" +
	"\x0fCheckNewVersion\x12,.processing.system.v1.CheckNewVersionRequest\x1a-.processing.system.v1.CheckNewVersionResponse\x12w\n" +
	"\x12UpdateToNewVersion\x12/.processing.system.v1.UpdateToNewVersionRequest\x1a0.processing.system.v1.UpdateToNewVersionResponse\x12b\n" +
	"\vGetLastLogs\x12(.processing.system.v1.GetLastLogsRequest\x1a).processing.system.v1.GetLastLogsResponseB\xdc\x01\n" +
	"\x18com.processing.system.v1B\vSystemProtoP\x01ZAgithub.com/dv-net/dv-processing/api/processing/system/v1;systemv1\xa2\x02\x03PSX\xaa\x02\x14Processing.System.V1\xca\x02\x14Processing\\System\\V1\xe2\x02 Processing\\System\\V1\\GPBMetadata\xea\x02\x16Processing::System::V1b\x06proto3"

var (
	file_processing_system_v1_system_proto_rawDescOnce sync.Once
	file_processing_system_v1_system_proto_rawDescData []byte
)

func file_processing_system_v1_system_proto_rawDescGZIP() []byte {
	file_processing_system_v1_system_proto_rawDescOnce.Do(func() {
		file_processing_system_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_processing_system_v1_system_proto_rawDesc), len(file_processing_system_v1_system_proto_rawDesc)))
	})
	return file_processing_system_v1_system_proto_rawDescData
}

var file_processing_system_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_processing_system_v1_system_proto_goTypes = []any{
	(*InfoRequest)(nil),                // 0: processing.system.v1.InfoRequest
	(*InfoResponse)(nil),               // 1: processing.system.v1.InfoResponse
	(*CheckNewVersionRequest)(nil),     // 2: processing.system.v1.CheckNewVersionRequest
	(*CheckNewVersionResponse)(nil),    // 3: processing.system.v1.CheckNewVersionResponse
	(*UpdateToNewVersionRequest)(nil),  // 4: processing.system.v1.UpdateToNewVersionRequest
	(*UpdateToNewVersionResponse)(nil), // 5: processing.system.v1.UpdateToNewVersionResponse
	(*GetLastLogsRequest)(nil),         // 6: processing.system.v1.GetLastLogsRequest
	(*LogEntry)(nil),                   // 7: processing.system.v1.LogEntry
	(*GetLastLogsResponse)(nil),        // 8: processing.system.v1.GetLastLogsResponse
	(*timestamppb.Timestamp)(nil),      // 9: google.protobuf.Timestamp
}
var file_processing_system_v1_system_proto_depIdxs = []int32{
	9, // 0: processing.system.v1.LogEntry.time:type_name -> google.protobuf.Timestamp
	7, // 1: processing.system.v1.GetLastLogsResponse.logs:type_name -> processing.system.v1.LogEntry
	0, // 2: processing.system.v1.SystemService.Info:input_type -> processing.system.v1.InfoRequest
	2, // 3: processing.system.v1.SystemService.CheckNewVersion:input_type -> processing.system.v1.CheckNewVersionRequest
	4, // 4: processing.system.v1.SystemService.UpdateToNewVersion:input_type -> processing.system.v1.UpdateToNewVersionRequest
	6, // 5: processing.system.v1.SystemService.GetLastLogs:input_type -> processing.system.v1.GetLastLogsRequest
	1, // 6: processing.system.v1.SystemService.Info:output_type -> processing.system.v1.InfoResponse
	3, // 7: processing.system.v1.SystemService.CheckNewVersion:output_type -> processing.system.v1.CheckNewVersionResponse
	5, // 8: processing.system.v1.SystemService.UpdateToNewVersion:output_type -> processing.system.v1.UpdateToNewVersionResponse
	8, // 9: processing.system.v1.SystemService.GetLastLogs:output_type -> processing.system.v1.GetLastLogsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_processing_system_v1_system_proto_init() }
func file_processing_system_v1_system_proto_init() {
	if File_processing_system_v1_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_processing_system_v1_system_proto_rawDesc), len(file_processing_system_v1_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_processing_system_v1_system_proto_goTypes,
		DependencyIndexes: file_processing_system_v1_system_proto_depIdxs,
		MessageInfos:      file_processing_system_v1_system_proto_msgTypes,
	}.Build()
	File_processing_system_v1_system_proto = out.File
	file_processing_system_v1_system_proto_goTypes = nil
	file_processing_system_v1_system_proto_depIdxs = nil
}
