// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: processing/client/v1/client.proto

package clientv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CallbackUrl    string                 `protobuf:"bytes,1,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	BackendIp      *string                `protobuf:"bytes,2,opt,name=backend_ip,json=backendIp,proto3,oneof" json:"backend_ip,omitempty"`
	MerchantDomain *string                `protobuf:"bytes,3,opt,name=merchant_domain,json=merchantDomain,proto3,oneof" json:"merchant_domain,omitempty"`
	BackendVersion string                 `protobuf:"bytes,4,opt,name=backend_version,json=backendVersion,proto3" json:"backend_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_processing_client_v1_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processing_client_v1_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_processing_client_v1_client_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *CreateRequest) GetBackendIp() string {
	if x != nil && x.BackendIp != nil {
		return *x.BackendIp
	}
	return ""
}

func (x *CreateRequest) GetMerchantDomain() string {
	if x != nil && x.MerchantDomain != nil {
		return *x.MerchantDomain
	}
	return ""
}

func (x *CreateRequest) GetBackendVersion() string {
	if x != nil {
		return x.BackendVersion
	}
	return ""
}

type CreateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientKey      string                 `protobuf:"bytes,2,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	AdminSecretKey string                 `protobuf:"bytes,3,opt,name=admin_secret_key,json=adminSecretKey,proto3" json:"admin_secret_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_processing_client_v1_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processing_client_v1_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_processing_client_v1_client_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateResponse) GetClientKey() string {
	if x != nil {
		return x.ClientKey
	}
	return ""
}

func (x *CreateResponse) GetAdminSecretKey() string {
	if x != nil {
		return x.AdminSecretKey
	}
	return ""
}

type UpdateCallbackURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CallbackUrl   string                 `protobuf:"bytes,2,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCallbackURLRequest) Reset() {
	*x = UpdateCallbackURLRequest{}
	mi := &file_processing_client_v1_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCallbackURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCallbackURLRequest) ProtoMessage() {}

func (x *UpdateCallbackURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processing_client_v1_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCallbackURLRequest.ProtoReflect.Descriptor instead.
func (*UpdateCallbackURLRequest) Descriptor() ([]byte, []int) {
	return file_processing_client_v1_client_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCallbackURLRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UpdateCallbackURLRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type UpdateCallbackURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCallbackURLResponse) Reset() {
	*x = UpdateCallbackURLResponse{}
	mi := &file_processing_client_v1_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCallbackURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCallbackURLResponse) ProtoMessage() {}

func (x *UpdateCallbackURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processing_client_v1_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCallbackURLResponse.ProtoReflect.Descriptor instead.
func (*UpdateCallbackURLResponse) Descriptor() ([]byte, []int) {
	return file_processing_client_v1_client_proto_rawDescGZIP(), []int{3}
}

type GetCallbackURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallbackURLRequest) Reset() {
	*x = GetCallbackURLRequest{}
	mi := &file_processing_client_v1_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallbackURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallbackURLRequest) ProtoMessage() {}

func (x *GetCallbackURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processing_client_v1_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallbackURLRequest.ProtoReflect.Descriptor instead.
func (*GetCallbackURLRequest) Descriptor() ([]byte, []int) {
	return file_processing_client_v1_client_proto_rawDescGZIP(), []int{4}
}

func (x *GetCallbackURLRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type GetCallbackURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallbackUrl   string                 `protobuf:"bytes,1,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCallbackURLResponse) Reset() {
	*x = GetCallbackURLResponse{}
	mi := &file_processing_client_v1_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCallbackURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCallbackURLResponse) ProtoMessage() {}

func (x *GetCallbackURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processing_client_v1_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCallbackURLResponse.ProtoReflect.Descriptor instead.
func (*GetCallbackURLResponse) Descriptor() ([]byte, []int) {
	return file_processing_client_v1_client_proto_rawDescGZIP(), []int{5}
}

func (x *GetCallbackURLResponse) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

var File_processing_client_v1_client_proto protoreflect.FileDescriptor

const file_processing_client_v1_client_proto_rawDesc = "" +
	"\n" +
	"!processing/client/v1/client.proto\x12\x14processing.client.v1\"\xd0\x01\n" +
	"\rCreateRequest\x12!\n" +
	"\fcallback_url\x18\x01 \x01(\tR\vcallbackUrl\x12\"\n" +
	"\n" +
	"backend_ip\x18\x02 \x01(\tH\x00R\tbackendIp\x88\x01\x01\x12,\n" +
	"\x0fmerchant_domain\x18\x03 \x01(\tH\x01R\x0emerchantDomain\x88\x01\x01\x12'\n" +
	"\x0fbackend_version\x18\x04 \x01(\tR\x0ebackendVersionB\r\n" +
	"\v_backend_ipB\x12\n" +
	"\x10_merchant_domain\"v\n" +
	"\x0eCreateResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"client_key\x18\x02 \x01(\tR\tclientKey\x12(\n" +
	"\x10admin_secret_key\x18\x03 \x01(\tR\x0eadminSecretKey\"Z\n" +
	"\x18UpdateCallbackURLRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12!\n" +
	"\fcallback_url\x18\x02 \x01(\tR\vcallbackUrl\"\x1b\n" +
	"\x19UpdateCallbackURLResponse\"4\n" +
	"\x15GetCallbackURLRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\";\n" +
	"\x16GetCallbackURLResponse\x12!\n" +
	"\fcallback_url\x18\x01 \x01(\tR\vcallbackUrl2\xc7\x02\n" +
	"\rClientService\x12S\n" +
	"\x06Create\x12#.processing.client.v1.CreateRequest\x1a$.processing.client.v1.CreateResponse\x12t\n" +
	"\x11UpdateCallbackURL\x12..processing.client.v1.UpdateCallbackURLRequest\x1a/.processing.client.v1.UpdateCallbackURLResponse\x12k\n" +
	"\x0eGetCallbackURL\x12+.processing.client.v1.GetCallbackURLRequest\x1a,.processing.client.v1.GetCallbackURLResponseB\xdc\x01\n" +
	"\x18com.processing.client.v1B\vClientProtoP\x01ZAgithub.com/dv-net/dv-processing/api/processing/client/v1;clientv1\xa2\x02\x03PCX\xaa\x02\x14Processing.Client.V1\xca\x02\x14Processing\\Client\\V1\xe2\x02 Processing\\Client\\V1\\GPBMetadata\xea\x02\x16Processing::Client::V1b\x06proto3"

var (
	file_processing_client_v1_client_proto_rawDescOnce sync.Once
	file_processing_client_v1_client_proto_rawDescData []byte
)

func file_processing_client_v1_client_proto_rawDescGZIP() []byte {
	file_processing_client_v1_client_proto_rawDescOnce.Do(func() {
		file_processing_client_v1_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_processing_client_v1_client_proto_rawDesc), len(file_processing_client_v1_client_proto_rawDesc)))
	})
	return file_processing_client_v1_client_proto_rawDescData
}

var file_processing_client_v1_client_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_processing_client_v1_client_proto_goTypes = []any{
	(*CreateRequest)(nil),             // 0: processing.client.v1.CreateRequest
	(*CreateResponse)(nil),            // 1: processing.client.v1.CreateResponse
	(*UpdateCallbackURLRequest)(nil),  // 2: processing.client.v1.UpdateCallbackURLRequest
	(*UpdateCallbackURLResponse)(nil), // 3: processing.client.v1.UpdateCallbackURLResponse
	(*GetCallbackURLRequest)(nil),     // 4: processing.client.v1.GetCallbackURLRequest
	(*GetCallbackURLResponse)(nil),    // 5: processing.client.v1.GetCallbackURLResponse
}
var file_processing_client_v1_client_proto_depIdxs = []int32{
	0, // 0: processing.client.v1.ClientService.Create:input_type -> processing.client.v1.CreateRequest
	2, // 1: processing.client.v1.ClientService.UpdateCallbackURL:input_type -> processing.client.v1.UpdateCallbackURLRequest
	4, // 2: processing.client.v1.ClientService.GetCallbackURL:input_type -> processing.client.v1.GetCallbackURLRequest
	1, // 3: processing.client.v1.ClientService.Create:output_type -> processing.client.v1.CreateResponse
	3, // 4: processing.client.v1.ClientService.UpdateCallbackURL:output_type -> processing.client.v1.UpdateCallbackURLResponse
	5, // 5: processing.client.v1.ClientService.GetCallbackURL:output_type -> processing.client.v1.GetCallbackURLResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_processing_client_v1_client_proto_init() }
func file_processing_client_v1_client_proto_init() {
	if File_processing_client_v1_client_proto != nil {
		return
	}
	file_processing_client_v1_client_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_processing_client_v1_client_proto_rawDesc), len(file_processing_client_v1_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_processing_client_v1_client_proto_goTypes,
		DependencyIndexes: file_processing_client_v1_client_proto_depIdxs,
		MessageInfos:      file_processing_client_v1_client_proto_msgTypes,
	}.Build()
	File_processing_client_v1_client_proto = out.File
	file_processing_client_v1_client_proto_goTypes = nil
	file_processing_client_v1_client_proto_depIdxs = nil
}
