// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_wallets

import (
	"context"

	"github.com/dv-net/dv-processing/pkg/walletsdk/wconstants"
	"github.com/google/uuid"
)

type Querier interface {
	MaxSequence(ctx context.Context, blockchain wconstants.BlockchainType, ownerID uuid.UUID) (int32, error)
}

var _ Querier = (*Queries)(nil)
