// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_settings

import (
	"context"

	"github.com/dv-net/dv-processing/internal/models"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.Setting, error)
	GetGlobalByName(ctx context.Context, name string) (*models.Setting, error)
	SetGlobal(ctx context.Context, name string, value string) (*models.Setting, error)
	Update(ctx context.Context, arg UpdateParams) (*models.Setting, error)
}

var _ Querier = (*Queries)(nil)
