// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_owners

import (
	"context"

	"github.com/dv-net/dv-processing/internal/models"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ConfirmTwoFactorAuth(ctx context.Context, id uuid.UUID) error
	Create(ctx context.Context, arg CreateParams) (*models.Owner, error)
	DisableTwoFactorAuth(ctx context.Context, otpSecret pgtype.Text, iD uuid.UUID) error
	ExistsByExternalID(ctx context.Context, externalID string) (bool, error)
	GetAll(ctx context.Context) ([]*models.Owner, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.Owner, error)
	SetOTPData(ctx context.Context, iD uuid.UUID, otpData pgtype.Text) error
	SetOTPSecret(ctx context.Context, iD uuid.UUID, otpSecret pgtype.Text) error
	UpdateMnemonic(ctx context.Context, iD uuid.UUID, mnemonic string) error
}

var _ Querier = (*Queries)(nil)
