// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: processed_blocks_gen.sql

package repo_processed_blocks

import (
	"context"

	"github.com/dv-net/dv-processing/pkg/walletsdk/wconstants"
)

const create = `-- name: Create :exec
INSERT INTO processed_blocks (blockchain, number, created_at)
	VALUES ($1, $2, now())
`

func (q *Queries) Create(ctx context.Context, blockchain wconstants.BlockchainType, number int64) error {
	_, err := q.db.Exec(ctx, create, blockchain, number)
	return err
}
