// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processed_blocks_gen.sql

package repo_processed_blocks

import (
	"context"

	"github.com/dv-net/dv-processing/pkg/walletsdk/wconstants"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :exec
INSERT INTO processed_blocks (blockchain, number, created_at, hash)
	VALUES ($1, $2, now(), $3)
`

type CreateParams struct {
	Blockchain wconstants.BlockchainType `db:"blockchain" json:"blockchain"`
	Number     int64                     `db:"number" json:"number"`
	Hash       pgtype.Text               `db:"hash" json:"hash"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.Exec(ctx, create, arg.Blockchain, arg.Number, arg.Hash)
	return err
}
