// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: processed.sql

package repo_processed_blocks

import (
	"context"

	"github.com/dv-net/dv-processing/pkg/walletsdk/wconstants"
)

const lastBlockNumber = `-- name: LastBlockNumber :one
select "number" from processed_blocks pb where pb.blockchain = $1 limit 1
`

func (q *Queries) LastBlockNumber(ctx context.Context, blockchain wconstants.BlockchainType) (int64, error) {
	row := q.db.QueryRow(ctx, lastBlockNumber, blockchain)
	var number int64
	err := row.Scan(&number)
	return number, err
}

const updateNumber = `-- name: UpdateNumber :exec
UPDATE processed_blocks SET "number" = $2, updated_at=now() WHERE blockchain = $1
`

func (q *Queries) UpdateNumber(ctx context.Context, blockchain wconstants.BlockchainType, number int64) error {
	_, err := q.db.Exec(ctx, updateNumber, blockchain, number)
	return err
}
