// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_processed_blocks

import (
	"context"

	"github.com/dv-net/dv-processing/internal/models"
	"github.com/dv-net/dv-processing/pkg/walletsdk/wconstants"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) error
	LastBlock(ctx context.Context, blockchain wconstants.BlockchainType) (*models.ProcessedBlock, error)
	LastBlockNumber(ctx context.Context, blockchain wconstants.BlockchainType) (int64, error)
	UpdateNumber(ctx context.Context, blockchain wconstants.BlockchainType, number int64) error
	UpdateNumberWithHash(ctx context.Context, arg UpdateNumberWithHashParams) error
}

var _ Querier = (*Queries)(nil)
