// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_processed_blocks

import (
	"context"

	"github.com/dv-net/dv-processing/pkg/walletsdk/wconstants"
)

type Querier interface {
	Create(ctx context.Context, blockchain wconstants.BlockchainType, number int64) error
	LastBlockNumber(ctx context.Context, blockchain wconstants.BlockchainType) (int64, error)
	UpdateNumber(ctx context.Context, blockchain wconstants.BlockchainType, number int64) error
}

var _ Querier = (*Queries)(nil)
