// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: processing/transfer/v1/transfer.proto

package transferv1

import (
	v1 "github.com/dv-net/dv-processing/api/processing/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transfer status
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_NEW         Status = 1
	Status_STATUS_PENDING     Status = 2
	Status_STATUS_PROCESSING  Status = 3
	Status_STATUS_IN_MEMPOOL  Status = 4
	Status_STATUS_UNCONFIRMED Status = 5
	Status_STATUS_COMPLETED   Status = 6
	Status_STATUS_FAILED      Status = 7
	Status_STATUS_FROZEN      Status = 8
	// Scheduled transfer was canceled before execution
	Status_STATUS_CANCELED Status = 9
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_NEW",
		2: "STATUS_PENDING",
		3: "STATUS_PROCESSING",
		4: "STATUS_IN_MEMPOOL",
		5: "STATUS_UNCONFIRMED",
		6: "STATUS_COMPLETED",
		7: "STATUS_FAILED",
		8: "STATUS_FROZEN",
		9: "STATUS_CANCELED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_NEW":         1,
		"STATUS_PENDING":     2,
		"STATUS_PROCESSING":  3,
		"STATUS_IN_MEMPOOL":  4,
		"STATUS_UNCONFIRMED": 5,
		"STATUS_COMPLETED":   6,
		"STATUS_FAILED":      7,
		"STATUS_FROZEN":      8,
		"STATUS_CANCELED":    9,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_processing_transfer_v1_transfer_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_processing_transfer_v1_transfer_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{0}
}

// Transfer transaction type
type TransferTransactionType int32

const (
	TransferTransactionType_TRANSFER_TRANSACTION_TYPE_UNSPECIFIED          TransferTransactionType = 0
	TransferTransactionType_TRANSFER_TRANSACTION_TYPE_TRANSFER             TransferTransactionType = 1
	TransferTransactionType_TRANSFER_TRANSACTION_TYPE_DELEGATE             TransferTransactionType = 2
	TransferTransactionType_TRANSFER_TRANSACTION_TYPE_RECLAIM              TransferTransactionType = 3
	TransferTransactionType_TRANSFER_TRANSACTION_TYPE_SEND_BURN_BASE_ASSET TransferTransactionType = 4
	TransferTransactionType_TRANSFER_TRANSACTION_TYPE_ACCOUNT_ACTIVATION   TransferTransactionType = 5
)

// Enum value maps for TransferTransactionType.
var (
	TransferTransactionType_name = map[int32]string{
		0: "TRANSFER_TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSFER_TRANSACTION_TYPE_TRANSFER",
		2: "TRANSFER_TRANSACTION_TYPE_DELEGATE",
		3: "TRANSFER_TRANSACTION_TYPE_RECLAIM",
		4: "TRANSFER_TRANSACTION_TYPE_SEND_BURN_BASE_ASSET",
		5: "TRANSFER_TRANSACTION_TYPE_ACCOUNT_ACTIVATION",
	}
	TransferTransactionType_value = map[string]int32{
		"TRANSFER_TRANSACTION_TYPE_UNSPECIFIED":          0,
		"TRANSFER_TRANSACTION_TYPE_TRANSFER":             1,
		"TRANSFER_TRANSACTION_TYPE_DELEGATE":             2,
		"TRANSFER_TRANSACTION_TYPE_RECLAIM":              3,
		"TRANSFER_TRANSACTION_TYPE_SEND_BURN_BASE_ASSET": 4,
		"TRANSFER_TRANSACTION_TYPE_ACCOUNT_ACTIVATION":   5,
	}
)

func (x TransferTransactionType) Enum() *TransferTransactionType {
	p := new(TransferTransactionType)
	*p = x
	return p
}

func (x TransferTransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferTransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_processing_transfer_v1_transfer_proto_enumTypes[1].Descriptor()
}

func (TransferTransactionType) Type() protoreflect.EnumType {
	return &file_processing_transfer_v1_transfer_proto_enumTypes[1]
}

func (x TransferTransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferTransactionType.Descriptor instead.
func (TransferTransactionType) EnumDescriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{1}
}

// Transfer transaction status
type TransferTransactionStatus int32

const (
	TransferTransactionStatus_TRANSFER_TRANSACTION_STATUS_UNSPECIFIED TransferTransactionStatus = 0
	TransferTransactionStatus_TRANSFER_TRANSACTION_STATUS_PENDING     TransferTransactionStatus = 1
	TransferTransactionStatus_TRANSFER_TRANSACTION_STATUS_UNCONFIRMED TransferTransactionStatus = 2
	TransferTransactionStatus_TRANSFER_TRANSACTION_STATUS_CONFIRMED   TransferTransactionStatus = 3
	TransferTransactionStatus_TRANSFER_TRANSACTION_STATUS_FAILED      TransferTransactionStatus = 4
)

// Enum value maps for TransferTransactionStatus.
var (
	TransferTransactionStatus_name = map[int32]string{
		0: "TRANSFER_TRANSACTION_STATUS_UNSPECIFIED",
		1: "TRANSFER_TRANSACTION_STATUS_PENDING",
		2: "TRANSFER_TRANSACTION_STATUS_UNCONFIRMED",
		3: "TRANSFER_TRANSACTION_STATUS_CONFIRMED",
		4: "TRANSFER_TRANSACTION_STATUS_FAILED",
	}
	TransferTransactionStatus_value = map[string]int32{
		"TRANSFER_TRANSACTION_STATUS_UNSPECIFIED": 0,
		"TRANSFER_TRANSACTION_STATUS_PENDING":     1,
		"TRANSFER_TRANSACTION_STATUS_UNCONFIRMED": 2,
		"TRANSFER_TRANSACTION_STATUS_CONFIRMED":   3,
		"TRANSFER_TRANSACTION_STATUS_FAILED":      4,
	}
)

func (x TransferTransactionStatus) Enum() *TransferTransactionStatus {
	p := new(TransferTransactionStatus)
	*p = x
	return p
}

func (x TransferTransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferTransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_processing_transfer_v1_transfer_proto_enumTypes[2].Descriptor()
}

func (TransferTransactionStatus) Type() protoreflect.EnumType {
	return &file_processing_transfer_v1_transfer_proto_enumTypes[2]
}

func (x TransferTransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferTransactionStatus.Descriptor instead.
func (TransferTransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{2}
}

// Transfer purpose
type TransferPurpose int32

const (
	// Regular transfer between owner's wallets (hot -> cold/processing, etc.)
	TransferPurpose_TRANSFER_PURPOSE_UNSPECIFIED TransferPurpose = 0
	// Withdrawal to an external address, requires TOTP and is executed immediately
	TransferPurpose_TRANSFER_PURPOSE_WITHDRAWAL TransferPurpose = 1
	// Refund of an incoming deposit (source_tx_hash) from a hot wallet.
	// Without TOTP it is executed after the configured cooldown, with TOTP - immediately
	TransferPurpose_TRANSFER_PURPOSE_REFUND TransferPurpose = 2
)

// Enum value maps for TransferPurpose.
var (
	TransferPurpose_name = map[int32]string{
		0: "TRANSFER_PURPOSE_UNSPECIFIED",
		1: "TRANSFER_PURPOSE_WITHDRAWAL",
		2: "TRANSFER_PURPOSE_REFUND",
	}
	TransferPurpose_value = map[string]int32{
		"TRANSFER_PURPOSE_UNSPECIFIED": 0,
		"TRANSFER_PURPOSE_WITHDRAWAL":  1,
		"TRANSFER_PURPOSE_REFUND":      2,
	}
)

func (x TransferPurpose) Enum() *TransferPurpose {
	p := new(TransferPurpose)
	*p = x
	return p
}

func (x TransferPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_processing_transfer_v1_transfer_proto_enumTypes[3].Descriptor()
}

func (TransferPurpose) Type() protoreflect.EnumType {
	return &file_processing_transfer_v1_transfer_proto_enumTypes[3]
}

func (x TransferPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferPurpose.Descriptor instead.
func (TransferPurpose) EnumDescriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{3}
}

// Wallet type of transfer source or destination
type WalletType int32

const (
	WalletType_WALLET_TYPE_UNSPECIFIED WalletType = 0
	WalletType_WALLET_TYPE_HOT         WalletType = 1
	WalletType_WALLET_TYPE_COLD        WalletType = 2
	WalletType_WALLET_TYPE_PROCESSING  WalletType = 3
	// Address does not belong to the owner
	WalletType_WALLET_TYPE_EXTERNAL WalletType = 4
)

// Enum value maps for WalletType.
var (
	WalletType_name = map[int32]string{
		0: "WALLET_TYPE_UNSPECIFIED",
		1: "WALLET_TYPE_HOT",
		2: "WALLET_TYPE_COLD",
		3: "WALLET_TYPE_PROCESSING",
		4: "WALLET_TYPE_EXTERNAL",
	}
	WalletType_value = map[string]int32{
		"WALLET_TYPE_UNSPECIFIED": 0,
		"WALLET_TYPE_HOT":         1,
		"WALLET_TYPE_COLD":        2,
		"WALLET_TYPE_PROCESSING":  3,
		"WALLET_TYPE_EXTERNAL":    4,
	}
)

func (x WalletType) Enum() *WalletType {
	p := new(WalletType)
	*p = x
	return p
}

func (x WalletType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletType) Descriptor() protoreflect.EnumDescriptor {
	return file_processing_transfer_v1_transfer_proto_enumTypes[4].Descriptor()
}

func (WalletType) Type() protoreflect.EnumType {
	return &file_processing_transfer_v1_transfer_proto_enumTypes[4]
}

func (x WalletType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletType.Descriptor instead.
func (WalletType) EnumDescriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{4}
}

// Transfer transaction
type TransferTransaction struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	Id                string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // UUID
	TransferId        string                    `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"` // UUID
	TxHash            string                    `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BandwidthAmount   string                    `protobuf:"bytes,4,opt,name=bandwidth_amount,json=bandwidthAmount,proto3" json:"bandwidth_amount,omitempty"`         // Decimal
	EnergyAmount      string                    `protobuf:"bytes,5,opt,name=energy_amount,json=energyAmount,proto3" json:"energy_amount,omitempty"`                  // Decimal
	NativeTokenAmount string                    `protobuf:"bytes,6,opt,name=native_token_amount,json=nativeTokenAmount,proto3" json:"native_token_amount,omitempty"` // Decimal
	NativeTokenFee    string                    `protobuf:"bytes,7,opt,name=native_token_fee,json=nativeTokenFee,proto3" json:"native_token_fee,omitempty"`          // Decimal
	TxType            TransferTransactionType   `protobuf:"varint,8,opt,name=tx_type,json=txType,proto3,enum=processing.transfer.v1.TransferTransactionType" json:"tx_type,omitempty"`
	Status            TransferTransactionStatus `protobuf:"varint,9,opt,name=status,proto3,enum=processing.transfer.v1.TransferTransactionStatus" json:"status,omitempty"`
	Step              string                    `protobuf:"bytes,10,opt,name=step,proto3" json:"step,omitempty"`
	CreatedAt         *timestamppb.Timestamp    `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp    `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransferTransaction) Reset() {
	*x = TransferTransaction{}
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTransaction) ProtoMessage() {}

func (x *TransferTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTransaction.ProtoReflect.Descriptor instead.
func (*TransferTransaction) Descriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *TransferTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransferTransaction) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferTransaction) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransferTransaction) GetBandwidthAmount() string {
	if x != nil {
		return x.BandwidthAmount
	}
	return ""
}

func (x *TransferTransaction) GetEnergyAmount() string {
	if x != nil {
		return x.EnergyAmount
	}
	return ""
}

func (x *TransferTransaction) GetNativeTokenAmount() string {
	if x != nil {
		return x.NativeTokenAmount
	}
	return ""
}

func (x *TransferTransaction) GetNativeTokenFee() string {
	if x != nil {
		return x.NativeTokenFee
	}
	return ""
}

func (x *TransferTransaction) GetTxType() TransferTransactionType {
	if x != nil {
		return x.TxType
	}
	return TransferTransactionType_TRANSFER_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *TransferTransaction) GetStatus() TransferTransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransferTransactionStatus_TRANSFER_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *TransferTransaction) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *TransferTransaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TransferTransaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Transfer
type Transfer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status          Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=processing.transfer.v1.Status" json:"status,omitempty"`
	OwnerId         string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	RequestId       string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Blockchain      v1.Blockchain          `protobuf:"varint,5,opt,name=blockchain,proto3,enum=processing.common.v1.Blockchain" json:"blockchain,omitempty"`
	FromAddresses   []string               `protobuf:"bytes,6,rep,name=from_addresses,json=fromAddresses,proto3" json:"from_addresses,omitempty"`
	ToAddresses     []string               `protobuf:"bytes,7,rep,name=to_addresses,json=toAddresses,proto3" json:"to_addresses,omitempty"`
	AssetIdentifier string                 `protobuf:"bytes,8,opt,name=asset_identifier,json=assetIdentifier,proto3" json:"asset_identifier,omitempty"`
	// used for tron transfers: burntrx, resources.
	// for other blockchains must be empty
	Kind             *string                `protobuf:"bytes,9,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	WholeAmount      bool                   `protobuf:"varint,10,opt,name=whole_amount,json=wholeAmount,proto3" json:"whole_amount,omitempty"`
	Amount           *string                `protobuf:"bytes,11,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	Fee              *string                `protobuf:"bytes,12,opt,name=fee,proto3,oneof" json:"fee,omitempty"`
	FeeMax           *string                `protobuf:"bytes,13,opt,name=fee_max,json=feeMax,proto3,oneof" json:"fee_max,omitempty"`
	TxHash           *string                `protobuf:"bytes,14,opt,name=tx_hash,json=txHash,proto3,oneof" json:"tx_hash,omitempty"`
	ErrorMessage     *string                `protobuf:"bytes,15,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	StateData        *structpb.Struct       `protobuf:"bytes,18,opt,name=state_data,json=stateData,proto3" json:"state_data,omitempty"`
	WorkflowSnapshot *structpb.Struct       `protobuf:"bytes,19,opt,name=workflow_snapshot,json=workflowSnapshot,proto3" json:"workflow_snapshot,omitempty"`
	// List of system transactions associated with the transfer, sorted by created_at
	Transactions []*TransferTransaction `protobuf:"bytes,20,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Purpose      TransferPurpose        `protobuf:"varint,21,opt,name=purpose,proto3,enum=processing.transfer.v1.TransferPurpose" json:"purpose,omitempty"`
	// Hash of the incoming deposit being refunded, set for refunds only
	SourceTxHash   *string    `protobuf:"bytes,22,opt,name=source_tx_hash,json=sourceTxHash,proto3,oneof" json:"source_tx_hash,omitempty"`
	WalletFromType WalletType `protobuf:"varint,23,opt,name=wallet_from_type,json=walletFromType,proto3,enum=processing.transfer.v1.WalletType" json:"wallet_from_type,omitempty"`
	WalletToType   WalletType `protobuf:"varint,24,opt,name=wallet_to_type,json=walletToType,proto3,enum=processing.transfer.v1.WalletType" json:"wallet_to_type,omitempty"`
	// Transfer is not picked up for execution before this time.
	// Empty for transfers executed immediately
	ExecuteAfter *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=execute_after,json=executeAfter,proto3,oneof" json:"execute_after,omitempty"`
	// Time the transfer was confirmed by owner's TOTP, empty if not confirmed
	TwoFactorConfirmedAt *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=two_factor_confirmed_at,json=twoFactorConfirmedAt,proto3,oneof" json:"two_factor_confirmed_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *Transfer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transfer) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Transfer) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Transfer) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Transfer) GetBlockchain() v1.Blockchain {
	if x != nil {
		return x.Blockchain
	}
	return v1.Blockchain(0)
}

func (x *Transfer) GetFromAddresses() []string {
	if x != nil {
		return x.FromAddresses
	}
	return nil
}

func (x *Transfer) GetToAddresses() []string {
	if x != nil {
		return x.ToAddresses
	}
	return nil
}

func (x *Transfer) GetAssetIdentifier() string {
	if x != nil {
		return x.AssetIdentifier
	}
	return ""
}

func (x *Transfer) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *Transfer) GetWholeAmount() bool {
	if x != nil {
		return x.WholeAmount
	}
	return false
}

func (x *Transfer) GetAmount() string {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return ""
}

func (x *Transfer) GetFee() string {
	if x != nil && x.Fee != nil {
		return *x.Fee
	}
	return ""
}

func (x *Transfer) GetFeeMax() string {
	if x != nil && x.FeeMax != nil {
		return *x.FeeMax
	}
	return ""
}

func (x *Transfer) GetTxHash() string {
	if x != nil && x.TxHash != nil {
		return *x.TxHash
	}
	return ""
}

func (x *Transfer) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *Transfer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transfer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Transfer) GetStateData() *structpb.Struct {
	if x != nil {
		return x.StateData
	}
	return nil
}

func (x *Transfer) GetWorkflowSnapshot() *structpb.Struct {
	if x != nil {
		return x.WorkflowSnapshot
	}
	return nil
}

func (x *Transfer) GetTransactions() []*TransferTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Transfer) GetPurpose() TransferPurpose {
	if x != nil {
		return x.Purpose
	}
	return TransferPurpose_TRANSFER_PURPOSE_UNSPECIFIED
}

func (x *Transfer) GetSourceTxHash() string {
	if x != nil && x.SourceTxHash != nil {
		return *x.SourceTxHash
	}
	return ""
}

func (x *Transfer) GetWalletFromType() WalletType {
	if x != nil {
		return x.WalletFromType
	}
	return WalletType_WALLET_TYPE_UNSPECIFIED
}

func (x *Transfer) GetWalletToType() WalletType {
	if x != nil {
		return x.WalletToType
	}
	return WalletType_WALLET_TYPE_UNSPECIFIED
}

func (x *Transfer) GetExecuteAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecuteAfter
	}
	return nil
}

func (x *Transfer) GetTwoFactorConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TwoFactorConfirmedAt
	}
	return nil
}

type CreateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OwnerId         string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	RequestId       string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Blockchain      v1.Blockchain          `protobuf:"varint,3,opt,name=blockchain,proto3,enum=processing.common.v1.Blockchain" json:"blockchain,omitempty"`
	FromAddresses   []string               `protobuf:"bytes,4,rep,name=from_addresses,json=fromAddresses,proto3" json:"from_addresses,omitempty"`
	ToAddresses     []string               `protobuf:"bytes,5,rep,name=to_addresses,json=toAddresses,proto3" json:"to_addresses,omitempty"`
	AssetIdentifier string                 `protobuf:"bytes,6,opt,name=asset_identifier,json=assetIdentifier,proto3" json:"asset_identifier,omitempty"`
	// withdraw the entire amount from the wallet
	WholeAmount bool    `protobuf:"varint,7,opt,name=whole_amount,json=wholeAmount,proto3" json:"whole_amount,omitempty"`
	Amount      *string `protobuf:"bytes,8,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	// delegate / burn / etc...
	Kind    *string         `protobuf:"bytes,9,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	Fee     *string         `protobuf:"bytes,10,opt,name=fee,proto3,oneof" json:"fee,omitempty"`
	FeeMax  *string         `protobuf:"bytes,11,opt,name=fee_max,json=feeMax,proto3,oneof" json:"fee_max,omitempty"`
	Purpose TransferPurpose `protobuf:"varint,12,opt,name=purpose,proto3,enum=processing.transfer.v1.TransferPurpose" json:"purpose,omitempty"`
	// Required for refunds: hash of the incoming deposit to the from address.
	// Amount must not exceed the deposited amount, one active refund per deposit
	SourceTxHash *string `protobuf:"bytes,13,opt,name=source_tx_hash,json=sourceTxHash,proto3,oneof" json:"source_tx_hash,omitempty"`
	// Owner's TOTP code. Required for withdrawals to external addresses,
	// optional for refunds (skips the cooldown)
	Totp          *string `protobuf:"bytes,14,opt,name=totp,proto3,oneof" json:"totp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateRequest) GetBlockchain() v1.Blockchain {
	if x != nil {
		return x.Blockchain
	}
	return v1.Blockchain(0)
}

func (x *CreateRequest) GetFromAddresses() []string {
	if x != nil {
		return x.FromAddresses
	}
	return nil
}

func (x *CreateRequest) GetToAddresses() []string {
	if x != nil {
		return x.ToAddresses
	}
	return nil
}

func (x *CreateRequest) GetAssetIdentifier() string {
	if x != nil {
		return x.AssetIdentifier
	}
	return ""
}

func (x *CreateRequest) GetWholeAmount() bool {
	if x != nil {
		return x.WholeAmount
	}
	return false
}

func (x *CreateRequest) GetAmount() string {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return ""
}

func (x *CreateRequest) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *CreateRequest) GetFee() string {
	if x != nil && x.Fee != nil {
		return *x.Fee
	}
	return ""
}

func (x *CreateRequest) GetFeeMax() string {
	if x != nil && x.FeeMax != nil {
		return *x.FeeMax
	}
	return ""
}

func (x *CreateRequest) GetPurpose() TransferPurpose {
	if x != nil {
		return x.Purpose
	}
	return TransferPurpose_TRANSFER_PURPOSE_UNSPECIFIED
}

func (x *CreateRequest) GetSourceTxHash() string {
	if x != nil && x.SourceTxHash != nil {
		return *x.SourceTxHash
	}
	return ""
}

func (x *CreateRequest) GetTotp() string {
	if x != nil && x.Totp != nil {
		return *x.Totp
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Transfer              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResponse) GetItem() *Transfer {
	if x != nil {
		return x.Item
	}
	return nil
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CancelRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Transfer              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{5}
}

func (x *CancelResponse) GetItem() *Transfer {
	if x != nil {
		return x.Item
	}
	return nil
}

type ExecuteNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Totp          string                 `protobuf:"bytes,3,opt,name=totp,proto3" json:"totp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteNowRequest) Reset() {
	*x = ExecuteNowRequest{}
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteNowRequest) ProtoMessage() {}

func (x *ExecuteNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteNowRequest.ProtoReflect.Descriptor instead.
func (*ExecuteNowRequest) Descriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteNowRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ExecuteNowRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteNowRequest) GetTotp() string {
	if x != nil {
		return x.Totp
	}
	return ""
}

type ExecuteNowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Transfer              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteNowResponse) Reset() {
	*x = ExecuteNowResponse{}
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteNowResponse) ProtoMessage() {}

func (x *ExecuteNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteNowResponse.ProtoReflect.Descriptor instead.
func (*ExecuteNowResponse) Descriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteNowResponse) GetItem() *Transfer {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetByRequestIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByRequestIDRequest) Reset() {
	*x = GetByRequestIDRequest{}
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByRequestIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByRequestIDRequest) ProtoMessage() {}

func (x *GetByRequestIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByRequestIDRequest.ProtoReflect.Descriptor instead.
func (*GetByRequestIDRequest) Descriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{8}
}

func (x *GetByRequestIDRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetByRequestIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Transfer              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByRequestIDResponse) Reset() {
	*x = GetByRequestIDResponse{}
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByRequestIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByRequestIDResponse) ProtoMessage() {}

func (x *GetByRequestIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_processing_transfer_v1_transfer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByRequestIDResponse.ProtoReflect.Descriptor instead.
func (*GetByRequestIDResponse) Descriptor() ([]byte, []int) {
	return file_processing_transfer_v1_transfer_proto_rawDescGZIP(), []int{9}
}

func (x *GetByRequestIDResponse) GetItem() *Transfer {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_processing_transfer_v1_transfer_proto protoreflect.FileDescriptor

const file_processing_transfer_v1_transfer_proto_rawDesc = "" +
	"\n" +
	"%processing/transfer/v1/transfer.proto\x12\x16processing.transfer.v1\x1a!processing/common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa8\x04\n" +
	"\x13TransferTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\tR\n" +
	"transferId\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12)\n" +
	"\x10bandwidth_amount\x18\x04 \x01(\tR\x0fbandwidthAmount\x12#\n" +
	"\renergy_amount\x18\x05 \x01(\tR\fenergyAmount\x12.\n" +
	"\x13native_token_amount\x18\x06 \x01(\tR\x11nativeTokenAmount\x12(\n" +
	"\x10native_token_fee\x18\a \x01(\tR\x0enativeTokenFee\x12H\n" +
	"\atx_type\x18\b \x01(\x0e2/.processing.transfer.v1.TransferTransactionTypeR\x06txType\x12I\n" +
	"\x06status\x18\t \x01(\x0e21.processing.transfer.v1.TransferTransactionStatusR\x06status\x12\x12\n" +
	"\x04step\x18\n" +
	" \x01(\tR\x04step\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9d\v\n" +
	"\bTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.processing.transfer.v1.StatusR\x06status\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12@\n" +
	"\n" +
	"blockchain\x18\x05 \x01(\x0e2 .processing.common.v1.BlockchainR\n" +
	"blockchain\x12%\n" +
	"\x0efrom_addresses\x18\x06 \x03(\tR\rfromAddresses\x12!\n" +
	"\fto_addresses\x18\a \x03(\tR\vtoAddresses\x12)\n" +
	"\x10asset_identifier\x18\b \x01(\tR\x0fassetIdentifier\x12\x17\n" +
	"\x04kind\x18\t \x01(\tH\x00R\x04kind\x88\x01\x01\x12!\n" +
	"\fwhole_amount\x18\n" +
	" \x01(\bR\vwholeAmount\x12\x1b\n" +
	"\x06amount\x18\v \x01(\tH\x01R\x06amount\x88\x01\x01\x12\x15\n" +
	"\x03fee\x18\f \x01(\tH\x02R\x03fee\x88\x01\x01\x12\x1c\n" +
	"\afee_max\x18\r \x01(\tH\x03R\x06feeMax\x88\x01\x01\x12\x1c\n" +
	"\atx_hash\x18\x0e \x01(\tH\x04R\x06txHash\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x0f \x01(\tH\x05R\ferrorMessage\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampH\x06R\tupdatedAt\x88\x01\x01\x126\n" +
	"\n" +
	"state_data\x18\x12 \x01(\v2\x17.google.protobuf.StructR\tstateData\x12D\n" +
	"\x11workflow_snapshot\x18\x13 \x01(\v2\x17.google.protobuf.StructR\x10workflowSnapshot\x12O\n" +
	"\ftransactions\x18\x14 \x03(\v2+.processing.transfer.v1.TransferTransactionR\ftransactions\x12A\n" +
	"\apurpose\x18\x15 \x01(\x0e2'.processing.transfer.v1.TransferPurposeR\apurpose\x12)\n" +
	"\x0esource_tx_hash\x18\x16 \x01(\tH\aR\fsourceTxHash\x88\x01\x01\x12L\n" +
	"\x10wallet_from_type\x18\x17 \x01(\x0e2\".processing.transfer.v1.WalletTypeR\x0ewalletFromType\x12H\n" +
	"\x0ewallet_to_type\x18\x18 \x01(\x0e2\".processing.transfer.v1.WalletTypeR\fwalletToType\x12D\n" +
	"\rexecute_after\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampH\bR\fexecuteAfter\x88\x01\x01\x12V\n" +
	"\x17two_factor_confirmed_at\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampH\tR\x14twoFactorConfirmedAt\x88\x01\x01B\a\n" +
	"\x05_kindB\t\n" +
	"\a_amountB\x06\n" +
	"\x04_feeB\n" +
	"\n" +
	"\b_fee_maxB\n" +
	"\n" +
	"\b_tx_hashB\x10\n" +
	"\x0e_error_messageB\r\n" +
	"\v_updated_atB\x11\n" +
	"\x0f_source_tx_hashB\x10\n" +
	"\x0e_execute_afterB\x1a\n" +
	"\x18_two_factor_confirmed_at\"\xd9\x04\n" +
	"\rCreateRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12@\n" +
	"\n" +
	"blockchain\x18\x03 \x01(\x0e2 .processing.common.v1.BlockchainR\n" +
	"blockchain\x12%\n" +
	"\x0efrom_addresses\x18\x04 \x03(\tR\rfromAddresses\x12!\n" +
	"\fto_addresses\x18\x05 \x03(\tR\vtoAddresses\x12)\n" +
	"\x10asset_identifier\x18\x06 \x01(\tR\x0fassetIdentifier\x12!\n" +
	"\fwhole_amount\x18\a \x01(\bR\vwholeAmount\x12\x1b\n" +
	"\x06amount\x18\b \x01(\tH\x00R\x06amount\x88\x01\x01\x12\x17\n" +
	"\x04kind\x18\t \x01(\tH\x01R\x04kind\x88\x01\x01\x12\x15\n" +
	"\x03fee\x18\n" +
	" \x01(\tH\x02R\x03fee\x88\x01\x01\x12\x1c\n" +
	"\afee_max\x18\v \x01(\tH\x03R\x06feeMax\x88\x01\x01\x12A\n" +
	"\apurpose\x18\f \x01(\x0e2'.processing.transfer.v1.TransferPurposeR\apurpose\x12)\n" +
	"\x0esource_tx_hash\x18\r \x01(\tH\x04R\fsourceTxHash\x88\x01\x01\x12\x17\n" +
	"\x04totp\x18\x0e \x01(\tH\x05R\x04totp\x88\x01\x01B\t\n" +
	"\a_amountB\a\n" +
	"\x05_kindB\x06\n" +
	"\x04_feeB\n" +
	"\n" +
	"\b_fee_maxB\x11\n" +
	"\x0f_source_tx_hashB\a\n" +
	"\x05_totp\"F\n" +
	"\x0eCreateResponse\x124\n" +
	"\x04item\x18\x01 \x01(\v2 .processing.transfer.v1.TransferR\x04item\"I\n" +
	"\rCancelRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"F\n" +
	"\x0eCancelResponse\x124\n" +
	"\x04item\x18\x01 \x01(\v2 .processing.transfer.v1.TransferR\x04item\"a\n" +
	"\x11ExecuteNowRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x12\n" +
	"\x04totp\x18\x03 \x01(\tR\x04totp\"J\n" +
	"\x12ExecuteNowResponse\x124\n" +
	"\x04item\x18\x01 \x01(\v2 .processing.transfer.v1.TransferR\x04item\"6\n" +
	"\x15GetByRequestIDRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"N\n" +
	"\x16GetByRequestIDResponse\x124\n" +
	"\x04item\x18\x01 \x01(\v2 .processing.transfer.v1.TransferR\x04item*\xdb\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"STATUS_NEW\x10\x01\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x02\x12\x15\n" +
	"\x11STATUS_PROCESSING\x10\x03\x12\x15\n" +
	"\x11STATUS_IN_MEMPOOL\x10\x04\x12\x16\n" +
	"\x12STATUS_UNCONFIRMED\x10\x05\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x06\x12\x11\n" +
	"\rSTATUS_FAILED\x10\a\x12\x11\n" +
	"\rSTATUS_FROZEN\x10\b\x12\x13\n" +
	"\x0fSTATUS_CANCELED\x10\t*\xa1\x02\n" +
	"\x17TransferTransactionType\x12)\n" +
	"%TRANSFER_TRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"TRANSFER_TRANSACTION_TYPE_TRANSFER\x10\x01\x12&\n" +
	"\"TRANSFER_TRANSACTION_TYPE_DELEGATE\x10\x02\x12%\n" +
	"!TRANSFER_TRANSACTION_TYPE_RECLAIM\x10\x03\x122\n" +
	".TRANSFER_TRANSACTION_TYPE_SEND_BURN_BASE_ASSET\x10\x04\x120\n" +
	",TRANSFER_TRANSACTION_TYPE_ACCOUNT_ACTIVATION\x10\x05*\xf1\x01\n" +
	"\x19TransferTransactionStatus\x12+\n" +
	"'TRANSFER_TRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12'\n" +
	"#TRANSFER_TRANSACTION_STATUS_PENDING\x10\x01\x12+\n" +
	"'TRANSFER_TRANSACTION_STATUS_UNCONFIRMED\x10\x02\x12)\n" +
	"%TRANSFER_TRANSACTION_STATUS_CONFIRMED\x10\x03\x12&\n" +
	"\"TRANSFER_TRANSACTION_STATUS_FAILED\x10\x04*q\n" +
	"\x0fTransferPurpose\x12 \n" +
	"\x1cTRANSFER_PURPOSE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTRANSFER_PURPOSE_WITHDRAWAL\x10\x01\x12\x1b\n" +
	"\x17TRANSFER_PURPOSE_REFUND\x10\x02*\x8a\x01\n" +
	"\n" +
	"WalletType\x12\x1b\n" +
	"\x17WALLET_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fWALLET_TYPE_HOT\x10\x01\x12\x14\n" +
	"\x10WALLET_TYPE_COLD\x10\x02\x12\x1a\n" +
	"\x16WALLET_TYPE_PROCESSING\x10\x03\x12\x18\n" +
	"\x14WALLET_TYPE_EXTERNAL\x10\x042\x99\x03\n" +
	"\x0fTransferService\x12W\n" +
	"\x06Create\x12%.processing.transfer.v1.CreateRequest\x1a&.processing.transfer.v1.CreateResponse\x12o\n" +
	"\x0eGetByRequestID\x12-.processing.transfer.v1.GetByRequestIDRequest\x1a..processing.transfer.v1.GetByRequestIDResponse\x12W\n" +
	"\x06Cancel\x12%.processing.transfer.v1.CancelRequest\x1a&.processing.transfer.v1.CancelResponse\x12c\n" +
	"\n" +
	"ExecuteNow\x12).processing.transfer.v1.ExecuteNowRequest\x1a*.processing.transfer.v1.ExecuteNowResponseB\xec\x01\n" +
	"\x1acom.processing.transfer.v1B\rTransferProtoP\x01ZEgithub.com/dv-net/dv-processing/api/processing/transfer/v1;transferv1\xa2\x02\x03PTX\xaa\x02\x16Processing.Transfer.V1\xca\x02\x16Processing\\Transfer\\V1\xe2\x02\"Processing\\Transfer\\V1\\GPBMetadata\xea\x02\x18Processing::Transfer::V1b\x06proto3"

var (
	file_processing_transfer_v1_transfer_proto_rawDescOnce sync.Once
	file_processing_transfer_v1_transfer_proto_rawDescData []byte
)

func file_processing_transfer_v1_transfer_proto_rawDescGZIP() []byte {
	file_processing_transfer_v1_transfer_proto_rawDescOnce.Do(func() {
		file_processing_transfer_v1_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_processing_transfer_v1_transfer_proto_rawDesc), len(file_processing_transfer_v1_transfer_proto_rawDesc)))
	})
	return file_processing_transfer_v1_transfer_proto_rawDescData
}

var file_processing_transfer_v1_transfer_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_processing_transfer_v1_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_processing_transfer_v1_transfer_proto_goTypes = []any{
	(Status)(0),                    // 0: processing.transfer.v1.Status
	(TransferTransactionType)(0),   // 1: processing.transfer.v1.TransferTransactionType
	(TransferTransactionStatus)(0), // 2: processing.transfer.v1.TransferTransactionStatus
	(TransferPurpose)(0),           // 3: processing.transfer.v1.TransferPurpose
	(WalletType)(0),                // 4: processing.transfer.v1.WalletType
	(*TransferTransaction)(nil),    // 5: processing.transfer.v1.TransferTransaction
	(*Transfer)(nil),               // 6: processing.transfer.v1.Transfer
	(*CreateRequest)(nil),          // 7: processing.transfer.v1.CreateRequest
	(*CreateResponse)(nil),         // 8: processing.transfer.v1.CreateResponse
	(*CancelRequest)(nil),          // 9: processing.transfer.v1.CancelRequest
	(*CancelResponse)(nil),         // 10: processing.transfer.v1.CancelResponse
	(*ExecuteNowRequest)(nil),      // 11: processing.transfer.v1.ExecuteNowRequest
	(*ExecuteNowResponse)(nil),     // 12: processing.transfer.v1.ExecuteNowResponse
	(*GetByRequestIDRequest)(nil),  // 13: processing.transfer.v1.GetByRequestIDRequest
	(*GetByRequestIDResponse)(nil), // 14: processing.transfer.v1.GetByRequestIDResponse
	(*timestamppb.Timestamp)(nil),  // 15: google.protobuf.Timestamp
	(v1.Blockchain)(0),             // 16: processing.common.v1.Blockchain
	(*structpb.Struct)(nil),        // 17: google.protobuf.Struct
}
var file_processing_transfer_v1_transfer_proto_depIdxs = []int32{
	1,  // 0: processing.transfer.v1.TransferTransaction.tx_type:type_name -> processing.transfer.v1.TransferTransactionType
	2,  // 1: processing.transfer.v1.TransferTransaction.status:type_name -> processing.transfer.v1.TransferTransactionStatus
	15, // 2: processing.transfer.v1.TransferTransaction.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: processing.transfer.v1.TransferTransaction.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: processing.transfer.v1.Transfer.status:type_name -> processing.transfer.v1.Status
	16, // 5: processing.transfer.v1.Transfer.blockchain:type_name -> processing.common.v1.Blockchain
	15, // 6: processing.transfer.v1.Transfer.created_at:type_name -> google.protobuf.Timestamp
	15, // 7: processing.transfer.v1.Transfer.updated_at:type_name -> google.protobuf.Timestamp
	17, // 8: processing.transfer.v1.Transfer.state_data:type_name -> google.protobuf.Struct
	17, // 9: processing.transfer.v1.Transfer.workflow_snapshot:type_name -> google.protobuf.Struct
	5,  // 10: processing.transfer.v1.Transfer.transactions:type_name -> processing.transfer.v1.TransferTransaction
	3,  // 11: processing.transfer.v1.Transfer.purpose:type_name -> processing.transfer.v1.TransferPurpose
	4,  // 12: processing.transfer.v1.Transfer.wallet_from_type:type_name -> processing.transfer.v1.WalletType
	4,  // 13: processing.transfer.v1.Transfer.wallet_to_type:type_name -> processing.transfer.v1.WalletType
	15, // 14: processing.transfer.v1.Transfer.execute_after:type_name -> google.protobuf.Timestamp
	15, // 15: processing.transfer.v1.Transfer.two_factor_confirmed_at:type_name -> google.protobuf.Timestamp
	16, // 16: processing.transfer.v1.CreateRequest.blockchain:type_name -> processing.common.v1.Blockchain
	3,  // 17: processing.transfer.v1.CreateRequest.purpose:type_name -> processing.transfer.v1.TransferPurpose
	6,  // 18: processing.transfer.v1.CreateResponse.item:type_name -> processing.transfer.v1.Transfer
	6,  // 19: processing.transfer.v1.CancelResponse.item:type_name -> processing.transfer.v1.Transfer
	6,  // 20: processing.transfer.v1.ExecuteNowResponse.item:type_name -> processing.transfer.v1.Transfer
	6,  // 21: processing.transfer.v1.GetByRequestIDResponse.item:type_name -> processing.transfer.v1.Transfer
	7,  // 22: processing.transfer.v1.TransferService.Create:input_type -> processing.transfer.v1.CreateRequest
	13, // 23: processing.transfer.v1.TransferService.GetByRequestID:input_type -> processing.transfer.v1.GetByRequestIDRequest
	9,  // 24: processing.transfer.v1.TransferService.Cancel:input_type -> processing.transfer.v1.CancelRequest
	11, // 25: processing.transfer.v1.TransferService.ExecuteNow:input_type -> processing.transfer.v1.ExecuteNowRequest
	8,  // 26: processing.transfer.v1.TransferService.Create:output_type -> processing.transfer.v1.CreateResponse
	14, // 27: processing.transfer.v1.TransferService.GetByRequestID:output_type -> processing.transfer.v1.GetByRequestIDResponse
	10, // 28: processing.transfer.v1.TransferService.Cancel:output_type -> processing.transfer.v1.CancelResponse
	12, // 29: processing.transfer.v1.TransferService.ExecuteNow:output_type -> processing.transfer.v1.ExecuteNowResponse
	26, // [26:30] is the sub-list for method output_type
	22, // [22:26] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_processing_transfer_v1_transfer_proto_init() }
func file_processing_transfer_v1_transfer_proto_init() {
	if File_processing_transfer_v1_transfer_proto != nil {
		return
	}
	file_processing_transfer_v1_transfer_proto_msgTypes[1].OneofWrappers = []any{}
	file_processing_transfer_v1_transfer_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_processing_transfer_v1_transfer_proto_rawDesc), len(file_processing_transfer_v1_transfer_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_processing_transfer_v1_transfer_proto_goTypes,
		DependencyIndexes: file_processing_transfer_v1_transfer_proto_depIdxs,
		EnumInfos:         file_processing_transfer_v1_transfer_proto_enumTypes,
		MessageInfos:      file_processing_transfer_v1_transfer_proto_msgTypes,
	}.Build()
	File_processing_transfer_v1_transfer_proto = out.File
	file_processing_transfer_v1_transfer_proto_goTypes = nil
	file_processing_transfer_v1_transfer_proto_depIdxs = nil
}
