// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_transfer_transactions

import (
	"context"

	"github.com/dv-net/dv-processing/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.TransferTransaction, error)
	FindSystemTransactions(ctx context.Context, arg FindSystemTransactionsParams) ([]*models.TransferTransaction, error)
	FindTransactionByType(ctx context.Context, transferID uuid.UUID, txType models.TransferTransactionType) ([]*models.TransferTransaction, error)
	GetAllByTransfer(ctx context.Context, transferID uuid.UUID) ([]*models.TransferTransaction, error)
	GetByTransfer(ctx context.Context, transferID uuid.UUID) ([]*models.TransferTransaction, error)
	UpdatePendingTxExpense(ctx context.Context, arg UpdatePendingTxExpenseParams) error
	UpdateStatus(ctx context.Context, iD uuid.UUID, status models.TransferTransactionsStatus) error
}

var _ Querier = (*Queries)(nil)
