// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo_webhooks

import (
	"context"

	"github.com/dv-net/dv-processing/internal/models"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	Cleanup(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	Create(ctx context.Context, arg []CreateParams) *CreateBatchResults
	DeleteByID(ctx context.Context, id uuid.UUID) error
	Exists(ctx context.Context, payload []byte, payload_2 []byte) (bool, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.WebhookView, error)
	GetUnsent(ctx context.Context, status models.WebhookStatus, limit int32) ([]*models.WebhookView, error)
	IncrementAttempt(ctx context.Context, iD uuid.UUID, response pgtype.Text) error
	SetSentAtNow(ctx context.Context, iD uuid.UUID, response pgtype.Text) error
}

var _ Querier = (*Queries)(nil)
