// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks_gen.sql

package repo_webhooks

import (
	"context"

	"github.com/google/uuid"
)

const deleteByID = `-- name: DeleteByID :exec
DELETE FROM webhooks WHERE id=$1
`

func (q *Queries) DeleteByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteByID, id)
	return err
}
