// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_wallets_processing

import (
	"context"

	"github.com/dv-net/dv-processing/internal/models"
	"github.com/dv-net/dv-processing/pkg/walletsdk/wconstants"
	"github.com/google/uuid"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*models.ProcessingWallet, error)
	Get(ctx context.Context, blockchain wconstants.BlockchainType, address string) (*models.ProcessingWallet, error)
	GetAllByOwnerID(ctx context.Context, ownerID uuid.UUID) ([]*models.ProcessingWallet, error)
	GetAllNotCreatedWallets(ctx context.Context, blockchains []string) ([]*GetAllNotCreatedWalletsRow, error)
	GetByBlockchain(ctx context.Context, ownerID uuid.UUID, blockchain wconstants.BlockchainType) (*models.ProcessingWallet, error)
	GetByBlockchainAndAddress(ctx context.Context, blockchain wconstants.BlockchainType, address string) (*models.ProcessingWallet, error)
	GetByOwnerID(ctx context.Context, ownerID uuid.UUID, blockchain wconstants.BlockchainType, address string) (*models.ProcessingWallet, error)
	IsTakenByAnotherOwner(ctx context.Context, ownerID uuid.UUID, address string) (bool, error)
}

var _ Querier = (*Queries)(nil)
