// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.12
package repo_wallets_hot

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameHotWallets TableName = "hot_wallets"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameHotWalletsId               ColumnName = "id"
	ColumnNameHotWalletsBlockchain       ColumnName = "blockchain"
	ColumnNameHotWalletsAddress          ColumnName = "address"
	ColumnNameHotWalletsOwnerId          ColumnName = "owner_id"
	ColumnNameHotWalletsExternalWalletId ColumnName = "external_wallet_id"
	ColumnNameHotWalletsSequence         ColumnName = "sequence"
	ColumnNameHotWalletsIsActivated      ColumnName = "is_activated"
	ColumnNameHotWalletsIsActive         ColumnName = "is_active"
	ColumnNameHotWalletsIsDirty          ColumnName = "is_dirty"
	ColumnNameHotWalletsCreatedAt        ColumnName = "created_at"
	ColumnNameHotWalletsUpdatedAt        ColumnName = "updated_at"
)

func HotWalletsColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameHotWalletsId,
		ColumnNameHotWalletsBlockchain,
		ColumnNameHotWalletsAddress,
		ColumnNameHotWalletsOwnerId,
		ColumnNameHotWalletsExternalWalletId,
		ColumnNameHotWalletsSequence,
		ColumnNameHotWalletsIsActivated,
		ColumnNameHotWalletsIsActive,
		ColumnNameHotWalletsIsDirty,
		ColumnNameHotWalletsCreatedAt,
		ColumnNameHotWalletsUpdatedAt,
	}
}
