// Code generated by pgxgen. DO NOT EDIT.
// versions:
//
//	pgxgen v0.3.12
package repo_transfers

import (
	"strings"

	"github.com/gobeam/stringy"
)

type TableName string

func (s TableName) String() string { return string(s) }

const (
	TableNameTransfers TableName = "transfers"
)

type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
	v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
	return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
	res := make([]string, len(s))
	for idx, colName := range s {
		res[idx] = colName.String()
	}
	return res
}

const (
	ColumnNameTransfersId               ColumnName = "id"
	ColumnNameTransfersStatus           ColumnName = "status"
	ColumnNameTransfersClientId         ColumnName = "client_id"
	ColumnNameTransfersOwnerId          ColumnName = "owner_id"
	ColumnNameTransfersRequestId        ColumnName = "request_id"
	ColumnNameTransfersBlockchain       ColumnName = "blockchain"
	ColumnNameTransfersFromAddresses    ColumnName = "from_addresses"
	ColumnNameTransfersToAddresses      ColumnName = "to_addresses"
	ColumnNameTransfersWalletFromType   ColumnName = "wallet_from_type"
	ColumnNameTransfersAssetIdentifier  ColumnName = "asset_identifier"
	ColumnNameTransfersKind             ColumnName = "kind"
	ColumnNameTransfersWholeAmount      ColumnName = "whole_amount"
	ColumnNameTransfersAmount           ColumnName = "amount"
	ColumnNameTransfersFee              ColumnName = "fee"
	ColumnNameTransfersFeeMax           ColumnName = "fee_max"
	ColumnNameTransfersTxHash           ColumnName = "tx_hash"
	ColumnNameTransfersCreatedAt        ColumnName = "created_at"
	ColumnNameTransfersUpdatedAt        ColumnName = "updated_at"
	ColumnNameTransfersStateData        ColumnName = "state_data"
	ColumnNameTransfersWorkflowSnapshot ColumnName = "workflow_snapshot"
)

func TransfersColumnNames() ColumnNames {
	return ColumnNames{
		ColumnNameTransfersId,
		ColumnNameTransfersStatus,
		ColumnNameTransfersClientId,
		ColumnNameTransfersOwnerId,
		ColumnNameTransfersRequestId,
		ColumnNameTransfersBlockchain,
		ColumnNameTransfersFromAddresses,
		ColumnNameTransfersToAddresses,
		ColumnNameTransfersWalletFromType,
		ColumnNameTransfersAssetIdentifier,
		ColumnNameTransfersKind,
		ColumnNameTransfersWholeAmount,
		ColumnNameTransfersAmount,
		ColumnNameTransfersFee,
		ColumnNameTransfersFeeMax,
		ColumnNameTransfersTxHash,
		ColumnNameTransfersCreatedAt,
		ColumnNameTransfersUpdatedAt,
		ColumnNameTransfersStateData,
		ColumnNameTransfersWorkflowSnapshot,
	}
}
