// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: clients.sql

package repo_clients

import (
	"context"

	"github.com/google/uuid"
)

const changeCallbackURL = `-- name: ChangeCallbackURL :exec
update clients set callback_url = $1, updated_at = now() where id = $2
`

func (q *Queries) ChangeCallbackURL(ctx context.Context, callbackUrl string, iD uuid.UUID) error {
	_, err := q.db.Exec(ctx, changeCallbackURL, callbackUrl, iD)
	return err
}
