// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_clients

import (
	"context"

	"github.com/dv-net/dv-processing/internal/models"
	"github.com/google/uuid"
)

type Querier interface {
	ChangeCallbackURL(ctx context.Context, callbackUrl string, iD uuid.UUID) error
	Create(ctx context.Context, secretKey string, callbackUrl string) (*models.Client, error)
	ExistsByID(ctx context.Context, id uuid.UUID) (bool, error)
	GetAll(ctx context.Context) ([]*models.Client, error)
	GetByID(ctx context.Context, id uuid.UUID) (*models.Client, error)
}

var _ Querier = (*Queries)(nil)
