// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo_processed_incidents

import (
	"context"

	"github.com/dv-net/dv-processing/internal/models"
	"github.com/dv-net/dv-processing/pkg/walletsdk/wconstants"
)

type Querier interface {
	CleanupOldIncidents(ctx context.Context) error
	GetIncompleteIncidents(ctx context.Context, blockchain wconstants.BlockchainType) ([]*models.ProcessedIncident, error)
	IsIncidentProcessed(ctx context.Context, blockchain wconstants.BlockchainType, iD string) (bool, error)
	MarkIncidentAsCompleted(ctx context.Context, blockchain wconstants.BlockchainType, iD string) error
	MarkIncidentAsFailed(ctx context.Context, arg MarkIncidentAsFailedParams) error
	MarkIncidentAsProcessing(ctx context.Context, arg MarkIncidentAsProcessingParams) error
}

var _ Querier = (*Queries)(nil)
